#%RAML 1.0
title: chatwork API
version: v2
baseUri: https://api.chatwork.com/
/job:
  get:
    displayName: getJob
    description: get the job
    queryParameters:
      job_id:
        description: Specify the jon id
        type:        integer
        minimum:     1
        maximum:     200
        default:     30
        example:     50
  post:
    displayName: createJob
    description: create a new job
    body:
      application/json:
        type: |
          {
            "id" : 5,
            "name" : "new job name"
          }
